// HOME PAGE DISPLAY 
/**
 * POPULAR MOVIE
 * POPULAR TV SHOW
 * POPULAR PERSON
 * TRENDING
 */
export const POPULAR_MOVIE = "POPULAR_MOVIE";
export const POPULAR_TV = "POPULAR_TV";
export const POPULAR_PERSON = "POPULAR_PERSON";
export const TRENDING = "TRENDING";



// SEARCH DATA
export const SEARCH_DATA = "SEARCH_DATA";


// INFO DETAILS
export const MOVIE_INFO = "MOVIE_INFO";
export const TVSHOW_INFO = "TVSHOW_INFO";
export const PERSON_INFO = "PERSON_INFO";
export const TRENDING_INFO = "TRENDING_INFO";
export const SEARCH_INFO = "SEARCH_INFO";



// INFO VIDEO DETAILS
export const VIDEO = "VIDEO";


// GENRES, LANGUAGE, SEASON
export const GENRES = "GENRES";
export const LANGUAGES = "LANGUAGES";
export const SEASON = "SEASON";



// CAST
export const MOVIE_CAST = "MOVIE_CAST";
export const TVSHOW_CAST = "TVSHOW_CAST";


// PERSON MOVIE LIST
export const PERSON_MOVIE_LIST = "PERSON_MOVIE_LIST";